name: Deploy production app

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Recover Gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - name: Download release certificate
      id: release_cert
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'erouska_release.jks'
        encodedString: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
    - name: Build release apps
      run: ./gradlew assembleRelease bundleProdRelease
      env:
        EROUSKA_RELEASE_KEYSTORE_PATH: ${{ steps.release_cert.outputs.filePath }}
        EROUSKA_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        EROUSKA_RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    - name: Publish artefact
      uses: actions/upload-artifact@v1
      with:
        name: app-releases
        path: app/build/outputs
    - name: Upload DEV app to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: 1:1077972356575:android:75624eb96818aa0d61886a
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: internal-test
        file: app/build/outputs/apk/dev/release/covid19-cz-dev-release.apk
    - name: Upload PROD app to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: 1:941144972907:android:937903c1584d72a673db2e
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: internal-test
        file: app/build/outputs/apk/prod/release/covid19-cz-prod-release.apk
